### ISSUE TITLE
FirebaseApp with name [DEFAULT] doesn't exist

### ISSUE THREAD

**Issue by Lluna** [ibm-bluemix-mobile-services/bms-samples-cordova-hellopush#12]
Hi,
I'm trying to run the example but i have this error in the function:

BMSPush.registerDevice({"userId":""}, success, failure);

com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushException: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist

I'm writting the sender Id from my Firebase app as userId, not sure if that is ok.. Do i need anything else?

thx

**Comment by AnanthaKrish** [comment]
Hi @Lluna , you ave to add the project package name in the Firebase under Android app section. You can get project package name from [config.xml](https://github.com/ibm-bluemix-mobile-services/bms-samples-cordova-hellopush/blob/master/config.xml) file.   The id will be in line number 2..

Here the project package name is **com.ibm.test1**

**Comment by Lluna** [comment]
yes i had added the project package name in the Firebase, also downloaded the play.service.json and added to my project. 
I have solved my issue adding this lines to build.gradle file:

 classpath 'com.google.gms:google-services:3.0.0'

apply plugin: 'com.google.gms.google-services'

Thx for reply!
