### ISSUE TITLE
Unable to register Android device

### ISSUE THREAD

**Issue by wirewolfdev** [ibm-bluemix-mobile-services/bms-samples-cordova-hellopush#5]
Hi,

Using this sample code, when I click the button to register the device I get the following message:

com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushException: Response: Status=401, Response Text: Error 401: Requires a valid clientSecret header

**Comment by jmeis** [comment]
You will need to disable the client secret header by making a PUT request to your service instance:

**PUT request:**

_Endpoint:_

`https://mobile.ng.bluemix.net/imfpush/v1/apps/PUSHAPPID/verifyClientSecret`

_Headers:_

`content-type: application/json, appSecret: APPSECRET`

_Body:_

`{"verifyClientSecret": false}`

---

A new SDK has been released that fixes this issue. This sample repository will be deprecated in the near-future, so I recommend building a new [Bluemix Mobile Starter](https://console.ng.bluemix.net/mobile/projects) with Cordova which makes the process a lot easier and faster for getting started.
